### ISSUE TITLE
Ask Thomas Session: eBPF Foundation & Cilium AWS announcement

### ISSUE THREAD

**Issue by tgraf** [isovalent/eCHO#35]
I'll be on eCHo Sep 17 answering questions around:
- eBPF Foundation
- Cilium AWS Announcement (EKS Anywhere)

Do you have questions? Feel free to ask them here as a reply and I'll answer them on Friday.

**Comment by grealish** [comment]
Great news!, i've a few questions i'd like drop ;) 

> eBPF Foundation

Is the Foundation working to bring this support on EKS Fargate instances? 
https://github.com/aws/containers-roadmap/issues/1027

> Cilium AWS Announcement (EKS Anywhere)
https://aws.amazon.com/blogs/aws/amazon-eks-anywhere-now-generally-available-to-create-and-manage-kubernetes-clusters-on-premises/

- For users with existing EKS deployments using other CNI's, e.g Calico, and extending out to EKS anywhere which is coming with Cilium CNI, is there a migration path for the region-based EKS deployment? 
e.g https://cilium.io/blog/2020/10/06/skybet-cilium-migration 
- In terms of AWS support, to what extend is AWS supporting technically Cilium CNI, is Isovalent upstream providing AWS support as a technology partner? Can AWS customers raise issues vi AWS Technical support channels?

**Comment by liquidat** [comment]
Another question posted on a channel:
> * what happens to iovisor

**Comment by liquidat** [comment]
Unfortunately we cannot do this session. But be sure to attend the session next week where we will have Justin from AWS to ask all your AWS related questions!

**Comment by grealish** [comment]
I'd recommend you have an AMA ticket, when it fills up,  schedule a eCHo ;) 
Looking forward when it gets re-scheduled
