### ISSUE TITLE
[Episode idea] bpfcov

### ISSUE THREAD

**Issue by leodido** [isovalent/eCHO#53]
Hello all,

recently, I did [bpfcov](https://github.com/elastic/bpfcov) to help all the eBPF aficionados obtain fine-grained code coverage of their eBPF programs when running in the Linux kernel, and to better understand their execution flow.

I think that exploring it in an episode, and presenting it, would be beneficial to the eBPF community.

Hope it makes sense to y'all, too. WDYT?

**Comment by lizrice** [comment]
Covered episode 38
