### ISSUE TITLE
Fix hyperlink in episode 20

### ISSUE THREAD

**Issue by faelis** [isovalent/eCHO#75]
Hi,
The link "Show notes" of the 20th episode has a typo :
https://github.com/isovalent/eCHO/blob/main/epsisodes/020
there is an extra lettre 'S' in the 'episodes' word.

**Comment by faelis** [comment]
done :)
https://github.com/isovalent/eCHO/pull/76

**Comment by xmulligan** [comment]
closed with #76 thanks for the help!
