### ISSUE TITLE
[Episode idea] cilium/ebpf

### ISSUE THREAD

**Issue by grantseltzer** [isovalent/eCHO#8]
I'd be interested in hearing about the various approaches, motivation, and vision for the [ebpf](https://github.com/cilium/ebpf) go package.

**Comment by lizrice** [comment]
We're going to cover this in [episode 23](https://youtu.be/8z2R13GRi5g) this Friday

**Comment by grantseltzer** [comment]
@lizrice Woo! Looking forward to it :D
