### ISSUE TITLE
[Episode Idea] XDP

### ISSUE THREAD

**Issue by simar7** [isovalent/eCHO#9]
I'd be interested in hearing the team thoughts on future XDP and related areas of work.

**Comment by lizrice** [comment]
Coming up this week! https://youtu.be/OIyPm6K4ooY

**Comment by lizrice** [comment]
[Show notes](https://github.com/isovalent/eCHO/tree/main/episodes/009)

Closing this as we covered so much in that episode, but shout if you have more questions that we should cover
